services:
  Xcentric\SimpleWorkflow\Service\ActionChain: ~

  Xcentric\SimpleWorkflow\Service\ConditionChain: ~

  Xcentric\SimpleWorkflow\Service\WorkflowQueueService:
    class: Xcentric\SimpleWorkflow\Service\WorkflowQueueService
    arguments: ['@service_container']

  Xcentric\SimpleWorkflow\Service\EntityChangeListener:
    class: Xcentric\SimpleWorkflow\Service\EntityChangeListener
    arguments: ['@service_container']
    tags:
      - { name: doctrine.event_listener, event: onFlush, connection: default }
      - { name: doctrine.event_listener, event: postFlush, connection: default }

  Xcentric\SimpleWorkflow\Service\HandleEntitiesEventService:
    class: Xcentric\SimpleWorkflow\Service\HandleEntitiesEventService
    arguments: ['@service_container', '@doctrine.orm.entity_manager']

  Xcentric\SimpleWorkflow\Service\Action\TestWorker:
    class: Xcentric\SimpleWorkflow\Service\Action\TestWorker
    arguments: ['@service_container']
    tags:
        - { name: "dtc_queue.worker" }
        - { name: "workflow.simple_action" }