services:
  Xcentric\SimpleWorkflow\Service\WorkflowQueueService:
    class: Xcentric\SimpleWorkflow\Service\WorkflowQueueService
    arguments: ['@doctrine.orm.entity_manager']

  Xcentric\SimpleWorkflow\EventListener\EntityChangeListener:
    class: Xcentric\SimpleWorkflow\EventListener\EntityChangeListener
    arguments:
      - '@service_container'
      - '@Xcentric\SimpleWorkflow\Service\WorkflowQueueService'
      - '@Xcentric\SimpleWorkflow\Service\HandleEntitiesEventService'
    tags:
      - { name: doctrine.event_listener, event: onFlush }
      - { name: doctrine.event_listener, event: postFlush }

  Xcentric\SimpleWorkflow\Service\HandleEntitiesEventService:
    class: Xcentric\SimpleWorkflow\Service\HandleEntitiesEventService
    arguments: ['@service_container', '@doctrine.orm.entity_manager']

  Xcentric\SimpleWorkflow\Service\Action\TestWorker:
    class: Xcentric\SimpleWorkflow\Service\Action\TestWorker
    arguments: ['@service_container']
    tags:
        - { name: "dtc_queue.worker" }
        - { name: "workflow.simple_action" }